server.port=${PORT:8080}
spring.main.allow-bean-definition-overriding=true

# Solo msj si hay error (logs generales)
logging.level.root=WARN

# Logs específicos del sistema de la laguna
logging.level.com.laventurosa=INFO